project:
  type: website
  output-dir: _site

website:

  navbar:
    background: "white"  # You can change this hex color to match your site
    foreground: "#666666"    # Text color
            
    # "right" items appear on the far right side
    right:
      - text: "Research"
        href: https://hanusa.xyz/research.html
      - text: "Portfolio"
        href: https://hanusa.xyz/portfolio.html
      - text: "Teaching"
        href: https://hanusa.xyz/teaching.html
      - text: "Leadership"
        href: https://hanusa.xyz/leadership.html
      - text: "Blog"
        href: https://hanusa.xyz/blog/
      - text: "Contact"
        href: https://hanusa.xyz/contact.html
        
sidebar:
    search: true       # Turn it on in the side menu
    contents:
      - index.qmd
      
format:
  html:
    grid:
      sidebar-width: 100px
    toc: true           # Turns on the Table of Contents
    toc-location: right # Ensures it stays on the right
    toc-title: "On this page"
