project:
  type: website
  output-dir: _site

website:
  search:
    location: sidebar
    type: textbox
    
  navbar:
    logo: "hanusa-xyz.png"       
    logo-href: https://hanusa.xyz 
    background: "white"  
    foreground: "#666666"    # Text color


    # "right" items appear on the far right side
    right:
      - text: "Research"
        href: https://hanusa.xyz/research.html
      - text: "Portfolio"
        href: https://hanusa.xyz/portfolio.html
      - text: "Teaching"
        href: https://hanusa.xyz/teaching.html
      - text: "Leadership"
        href: https://hanusa.xyz/leadership.html
      - text: "Blog"
        href: https://hanusa.xyz/blog/
      - text: "Contact"
        href: https://hanusa.xyz/contact.html

  sidebar:
    search: true
              
format:
  html:
    toc: true          
    toc-location: left 
    toc-title: "Contents" # Fallback if title is missing
    css: blog_styles.css  
